import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";

const onest = Onest({
	subsets: ["latin"], // ou ['latin-ext'], se precisar de mais caracteres
	weight: ["400", "500", "700"], // escolha os pesos que vai usar
	display: "swap",
});

export const metadata: Metadata = {
	title: "Ink down",
	description: "Generated by create next app",
	icons: {
		icon: "icon.svg",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-BR">
			<body
				className={`${onest.className} w-full h-[100vh] bg-zinc-200 dark:bg-zinc-800`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="light"
					enableSystem
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
