import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";

const onest = Onest({
  subsets: ['latin'], // ou ['latin-ext'], se precisar de mais caracteres
  weight: ['400', '500', '700'], // escolha os pesos que vai usar
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${onest.className}`}
      >
        {children}
      </body>
    </html>
  );
}
