import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";

const onest = Onest({
  subsets: ['latin'], // ou ['latin-ext'], se precisar de mais caracteres
  weight: ['400', '500', '700'], // escolha os pesos que vai usar
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Ink down",
  description: "Generated by create next app",
  icons: {
    icon: "icon.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${onest.className} w-full h-[350vh] bg-zinc-200`}
      >
        {children}
      </body>
    </html>
  );
}
