version: "3.9"

services:
  db:
    image: postgres:13
    container_name: ink-down-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ink-down'
    ports:
      - "5432:5432"
    volumes:
      - ink_db_data:/var/lib/postgresql/data
     # - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
volumes:
  ink_db_data: